class LanguageHelper {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title_1': 'FakeChat',
      'app_title_2': 'Studio',
      'my_conversations': 'My Conversations',
      'no_chats_yet': 'No chats yet',
      'tap_plus_to_create': 'Tap the + button to create\nyour first fake chat',
      'choose_platform': 'Choose Platform',
      'select_messaging_app': 'Select the messaging app to simulate',
      'messages': 'messages',
      'contact': 'Contact',
      'settings': 'Settings',
      'image': 'Image',
      'audio': 'Audio',
      'call': 'Call',
      'date': 'Date',
      'export': 'Export',
      'editor': 'Editor',
      'preview': 'Preview',
      'capture': 'Capture',
      'sender': 'Sender',
      'receiver': 'Receiver',
      'type_a_message': 'Type a message...',
      'edit_message': 'Edit Message',
      'add_message': 'Add Message',
      'delete': 'Delete',
      'save': 'Save',
      'cancel': 'Cancel',
      'screenshot_saved': 'Screenshot saved to gallery!',
      'capture_failed': 'Capture failed',
      'create_chat': 'Create Chat',
      'apply_settings': 'Apply Mockup Settings',
      'apply_contact': 'Apply Contact Settings',
      'choose_type': 'Choose Message Type',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'friday': 'Friday',
      'saturday': 'Saturday',
      'sunday': 'Sunday',
      'jan': 'Jan',
      'feb': 'Feb',
      'mar': 'Mar',
      'apr': 'Apr',
      'may': 'May',
      'jun': 'Jun',
      'jul': 'Jul',
      'aug': 'Aug',
      'sep': 'Sep',
      'oct': 'Oct',
      'nov': 'Nov',
      'dec': 'Dec',
      'january': 'January',
      'february': 'February',
      'march': 'March',
      'april': 'April',
      'june': 'June',
      'july': 'July',
      'august': 'August',
      'september': 'September',
      'october': 'October',
      'november': 'November',
      'december': 'December',
      'active_now': 'Active now',
      'online': 'online',
      'offline': 'offline',
      'last_seen_recently': 'last seen recently',
      'last_seen': 'last seen',
      'just_now': 'just now',
      'you': 'You',
      'sent': 'Sent',
      'typing': 'typing...',
      'no_messages_yet': 'No messages yet',
      'new_chat': 'New Chat',
      'new_snap': 'New Snap',
      'opened': 'Opened',
    },
    'ar': {
      'app_title_1': 'شات',
      'app_title_2': 'فيك',
      'my_conversations': 'محادثاتي المكتوبة',
      'no_chats_yet': 'لا توجد محادثات بعد',
      'tap_plus_to_create': 'اضغط على زر + لإنشاء\nمحادثتك الأولى المحاكاة',
      'choose_platform': 'اختر منصة الدردشة',
      'select_messaging_app': 'اختر تطبيق المراسلة للمحاكاة',
      'messages': 'رسائل',
      'contact': 'المستخدم',
      'settings': 'إعدادات الإطار',
      'image': 'صورة',
      'audio': 'تسجيل',
      'call': 'مكالمة',
      'date': 'تاريخ',
      'export': 'تصدير',
      'editor': 'المحرر',
      'preview': 'معاينة',
      'capture': 'صورة شاشة',
      'sender': 'أنا (اليمين)',
      'receiver': 'الطرف الآخر',
      'type_a_message': 'اكتب رسالتك المحاكاة...',
      'edit_message': 'تعديل الرسالة',
      'add_message': 'إضافة رسالة جديدة',
      'delete': 'حذف',
      'save': 'حفظ التعديلات',
      'cancel': 'إلغاء',
      'screenshot_saved': 'تم حفظ لقطة المحاكاة بنجاح في المعرض!',
      'capture_failed': 'فشل التقاط الصورة!',
      'create_chat': 'إنشاء محادثة جديدة',
      'apply_settings': 'تطبيق إعدادات الهاتف',
      'apply_contact': 'تطبيق بيانات الاتصال',
      'choose_type': 'اختر نوع محتوى الرسالة',
      'today': 'اليوم',
      'yesterday': 'أمس',
      'monday': 'الإثنين',
      'tuesday': 'الثلاثاء',
      'wednesday': 'الأربعاء',
      'thursday': 'الخميس',
      'friday': 'الجمعة',
      'saturday': 'السبت',
      'sunday': 'الأحد',
      'jan': 'يناير',
      'feb': 'فبراير',
      'mar': 'مارس',
      'apr': 'أبريل',
      'may': 'مايو',
      'jun': 'يونيو',
      'jul': 'يوليو',
      'aug': 'أغسطس',
      'sep': 'سبتمبر',
      'oct': 'أكتوبر',
      'nov': 'نوفمبر',
      'dec': 'ديسمبر',
      'january': 'يناير',
      'february': 'فبراير',
      'march': 'مارس',
      'april': 'أبريل',
      'june': 'يونيو',
      'july': 'يوليو',
      'august': 'أغسطس',
      'september': 'سبتمبر',
      'october': 'أكتوبر',
      'november': 'نوفمبر',
      'december': 'ديسمبر',
      'active_now': 'نشط الآن',
      'online': 'متصل الآن',
      'offline': 'غير متصل',
      'last_seen_recently': 'آخر ظهور كان قريبًا',
      'last_seen': 'آخر ظهور',
      'just_now': 'الآن',
      'you': 'أنت',
      'sent': 'أرسل',
      'typing': 'يكتب الآن...',
      'no_messages_yet': 'لا توجد رسائل بعد',
      'new_chat': 'دردشة جديدة',
      'new_snap': 'سناب جديد',
      'opened': 'تم الفتح',
    }
  };

  static String translate(String key, bool isArabic) {
    final lang = isArabic ? 'ar' : 'en';
    return _localizedValues[lang]?[key] ?? key;
  }

  static String translateDate(String label, bool isArabic) {
    final lower = label.trim().toLowerCase();
    final lang = isArabic ? 'ar' : 'en';
    if (_localizedValues['en']!.containsKey(lower) || _localizedValues['ar']!.containsKey(lower)) {
      return _localizedValues[lang]?[lower] ?? label;
    }
    return label;
  }
}
