class LanguageHelper {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title_1': 'FakeChat',
      'app_title_2': 'Studio',
      'my_conversations': 'My Conversations',
      'no_chats_yet': 'No chats yet',
      'tap_plus_to_create': 'Tap the + button to create\nyour first fake chat',
      'choose_platform': 'Choose Platform',
      'select_messaging_app': 'Select the messaging app to simulate',
      'messages': 'messages',
      'contact': 'Contact',
      'settings': 'Settings',
      'image': 'Image',
      'audio': 'Audio',
      'call': 'Call',
      'date': 'Date',
      'export': 'Export',
      'editor': 'Editor',
      'preview': 'Preview',
      'capture': 'Capture',
      'sender': 'Sender',
      'receiver': 'Receiver',
      'type_a_message': 'Type a message...',
      'edit_message': 'Edit Message',
      'add_message': 'Add Message',
      'delete': 'Delete',
      'save': 'Save',
      'cancel': 'Cancel',
      'screenshot_saved': 'Screenshot saved to gallery!',
      'capture_failed': 'Capture failed',
      'create_chat': 'Create Chat',
      'apply_settings': 'Apply Mockup Settings',
      'apply_contact': 'Apply Contact Settings',
      'choose_type': 'Choose Message Type',
    },
    'ar': {
      'app_title_1': 'شات',
      'app_title_2': 'فيك',
      'my_conversations': 'محادثاتي المكتوبة',
      'no_chats_yet': 'لا توجد محادثات بعد',
      'tap_plus_to_create': 'اضغط على زر + لإنشاء\nمحادثتك الأولى المحاكاة',
      'choose_platform': 'اختر منصة الدردشة',
      'select_messaging_app': 'اختر تطبيق المراسلة للمحاكاة',
      'messages': 'رسائل',
      'contact': 'المستخدم',
      'settings': 'إعدادات الإطار',
      'image': 'صورة',
      'audio': 'تسجيل',
      'call': 'مكالمة',
      'date': 'تاريخ',
      'export': 'تصدير',
      'editor': 'المحرر',
      'preview': 'معاينة',
      'capture': 'صورة شاشة',
      'sender': 'أنا (اليمين)',
      'receiver': 'الطرف الآخر',
      'type_a_message': 'اكتب رسالتك المحاكاة...',
      'edit_message': 'تعديل الرسالة',
      'add_message': 'إضافة رسالة جديدة',
      'delete': 'حذف',
      'save': 'حفظ التعديلات',
      'cancel': 'إلغاء',
      'screenshot_saved': 'تم حفظ لقطة المحاكاة بنجاح في المعرض!',
      'capture_failed': 'فشل التقاط الصورة!',
      'create_chat': 'إنشاء محادثة جديدة',
      'apply_settings': 'تطبيق إعدادات الهاتف',
      'apply_contact': 'تطبيق بيانات الاتصال',
      'choose_type': 'اختر نوع محتوى الرسالة',
    }
  };

  static String translate(String key, bool isArabic) {
    final lang = isArabic ? 'ar' : 'en';
    return _localizedValues[lang]?[key] ?? key;
  }
}
